apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sample-api:latest
        ports:
          - containerPort: 8080

        volumeMounts:
          - name: storage
            mountPath: /app/storage

        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"

          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_CONNECTION_STRING

          - name: Redis__ConnectionString
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REDIS_CONNECTION_STRING

          - name: SecretKeys__Jwt__key
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_KEY

          - name: SecretKeys__Jwt__ExpiryHours
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_EXPIRY_HOURS

          - name: SecretKeys__Jwt__ExpiryMinutes
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_EXPIRY_MINUTES

          - name: GoogleOAuth__ClientId
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: GOOGLE_CLIENT_ID

          - name: GoogleOAuth__ClientSecret
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: GOOGLE_CLIENT_SECRET

          - name: FileStorage__BasePath
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: FILE_STORAGE_PATH

          - name: EmailSettings__Host
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: EMAIL_HOST

          - name: EmailSettings__Port
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: EMAIL_PORT

          - name: EmailSettings__Username
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: EMAIL_USERNAME

          - name: EmailSettings__Password
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: EMAIL_PASSWORD

          - name: StartUpRole__Admin
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ROLE_NAME_ADMIN

          - name: StartUpRole__User
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ROLE_NAME_USER

        startupProbe:
          httpGet:
            path: /health/live
            port: 8080
          failureThreshold: 30
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080

      volumes:
      - name: storage
        hostPath:
          path: "/run/desktop/mnt/host/d/AppStorage"
          type: DirectoryOrCreate