name: Local Full CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .NET app
        run: dotnet build

      - name: Run tests
        run: dotnet test

      - name: Build Docker image
        run: docker build -t sample-api:latest .

      # Create namespace if missing
      - name: Ensure namespace exists
        run: |
          kubectl create namespace sample --dry-run=client -o yaml | kubectl apply -f -

      # Recreate secret.yml from GitHub Secret
      - name: Generate Kubernetes Secret File
        shell: powershell
        run: |
          @"
          ${{ secrets.K8S_SECRET_YAML }}
          "@ | Out-File -FilePath k8s/secret.yml -Encoding utf8

      # Deploy all manifests using kustomize
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s
          kubectl rollout status deployment/api -n sample